### ISSUE TITLE
Practica6

### ISSUE THREAD

**Issue by Sandra631** [SistemasTecTlaxiaco/practica-de-hilos-Sandra631#2]
[PRACTICA6_TOPICOSAVANZADOS.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-Sandra631/files/8447851/PRACTICA6_TOPICOSAVANZADOS.pdf)

**Comment by IrvingFernand0** [comment]
Calificación: 18

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
